language: node_js
node_js:
  - '9'
dist: trusty
sudo: required
branches:
  only:
    - master
before_script:
  - npm install -g @angular/cli
  - npm i angular-cli-ghpages
script:
  - ng build --prod --base-href https://sutin1234.github.io/Angular7-Travis-CI
  - ngh --message="auto deploy"
  - ngh --branch=production
  - ngh --dry-run
